name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - rid: linux-x64
            os: linux
            arch: x64
            runner: ubuntu-latest
          - rid: osx-x64
            os: darwin
            arch: x64
            runner: macos-13
          - rid: osx-arm64
            os: darwin
            arch: arm64
            runner: macos-latest
          - rid: win-x64
            os: windows
            arch: x64
            runner: windows-latest

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish
      run: |
        dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true -p:PublishAot=true -p:StripSymbols=true -o ./publish/${{ matrix.rid }}

    - name: Create archive (Windows)
      if: matrix.os == 'windows'
      run: |
        cd ./publish/${{ matrix.rid }}
        Compress-Archive -Path * -DestinationPath ../../ecengine-${{ matrix.os }}-${{ matrix.arch }}.zip
      shell: powershell

    - name: Create archive (Unix)
      if: matrix.os != 'windows'
      run: |
        cd ./publish/${{ matrix.rid }}
        tar -czf ../../ecengine-${{ matrix.os }}-${{ matrix.arch }}.tar.gz *
      shell: bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ecengine-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          ecengine-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          ecengine-${{ matrix.os }}-${{ matrix.arch }}.zip

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ECEngine ${{ github.ref_name }}
        draft: false
        prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
        body: |
          ## ECEngine Release ${{ github.ref_name }}
          
          ### Installation
          
          **Quick Install (macOS, Linux, WSL):**
          ```bash
          curl -fsSL https://raw.githubusercontent.com/labidiaymen/ec-engine/main/install.sh | bash
          ```
          
          **Windows (PowerShell):**
          ```powershell
          iwr -useb https://raw.githubusercontent.com/labidiaymen/ec-engine/main/install.ps1 | iex
          ```
          
          **Manual Installation:**
          Download the appropriate binary for your platform below.
          
          After installation, the binary will be available as `eec`.
          
          ### Changes
          - See commit history for detailed changes
          
          ### Supported Platforms
          - Linux x64
          - macOS x64 (Intel)
          - macOS ARM64 (Apple Silicon)
          - Windows x64
        files: |
          ./artifacts/ecengine-linux-x64/ecengine-linux-x64.tar.gz
          ./artifacts/ecengine-darwin-x64/ecengine-darwin-x64.tar.gz
          ./artifacts/ecengine-darwin-arm64/ecengine-darwin-arm64.tar.gz
          ./artifacts/ecengine-windows-x64/ecengine-windows-x64.zip
